### ISSUE TITLE
[X] ERROR AL GENERAR SU BACKDOOR

### ISSUE THREAD

**Issue by tarikovish** [AdrMXR/KitHack#29]
[*] Generating payload...
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10193 bytes

[*] Decompiling original APK...
I: Using Apktool 2.4.1-dirty on original.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/btn_viewall.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/s_controller_bar_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/btn_bg_gray.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/btn_viewall_night.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/btn_viewall_night_press.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/btn_bg_white.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

[*] Decompiling payload APK...
I: Using Apktool 2.4.1-dirty on payload.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

[*] Configuring RAT Payload...

[*] Compiling RAT APK...
I: Using Apktool 2.4.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
	at brut.androlib.Androlib.buildSources(Androlib.java:349)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:251)
	at brut.apktool.Main.main(Main.java:79)

[X] ERROR AL GENERAR SU BACKDOOR

**Comment by AdrMXR** [comment]
Please provide the OS you have, the KitHack version you use, and your apktool version.

**Comment by k4li0** [comment]
I'll upload everything, maybe it's a misuse. . .

[*] Sys Payloads:                                                                                        
[01] LINUX --> Kithack.elf
[02] WINDOWS --> Kithack.exe
[03] ANDROID --> Kithack.apk
[04] MAC OS --> Kithack.macho                                                                             [05] PHP --> Kithack.php
[06] PYTHON --> Kithack.py                                                                                [07] BASH --> Kithack.sh
[08] PERL --> Kithack.pl
[09] RUN MSFCONSOLE
 [0] Back
KitHack >> 3

 [*] Select Payload:

[01] android/meterpreter_reverse_http
[02] android/meterpreter_reverse_https
[03] android/meterpreter_reverse_tcp
[04] android/meterpreter/reverse_tcp
[05] android/shell/reverse_http
[06] android/shell/reverse_https
[07] android/shell/reverse_tcp
KitHack >> 4                                                                                                                                                                                                         [*] Select APK Type:
                                                                                                          [01] APK MSF
[02] APK ORIGINAL
KitHack >> 2

 [*] Select Method:                                                                                       
[01] Use the old Metasploit method                                                                        [02] Use the new KitHack method
KitHack >> 2                                                                                                                                                                                                        Local IP: 10.164.9.218                                                                                    
Public IP: 132.184.131.228
                                                                                
(KitHack.py:7734): Gtk-CRITICAL **: 03:43:08.896: _gtk_css_lookup_resolve: assertion '(((__extension__ ({ GTypeInstance *__inst = (GTypeInstance*) ((provider)); GType __t = ((_gtk_style_provider_private_get_type ())); gboolean __r; if (!__inst) __r = (0); else if (__inst->g_class && __inst->g_class->g_type == __t) __r = (!(0)); else __r = g_type_check_instance_is_a (__inst, __t); __r; }))))' failed
/usr/local/lib/python3.11/dist-packages/zenipy/zenipy.py:89: Warning: g_object_set_data_full: assertion 'G_IS_OBJECT (object)' failed
  self.entry_widget = Gtk.Entry()

(KitHack.py:7734): Gtk-ERROR **: 03:43:08.905: Can't create a GtkStyleContext without a display connection/usr/local/bin/kithack: line 2:  7732 Trace/breakpoint trap   sudo python3 KitHack.py
