### ISSUE TITLE
Error after installation on Debian 10

### ISSUE THREAD

**Issue by xSnkz** [AdrMXR/KitHack#31]
I installed the Kithack like your in your Instructions and it works fine and then i will type in "kithack" and it gave me this error
Can you please help me?

Thanks in advance!
**root@localhost:~/KitHack# kithack
Traceback (most recent call last):
  File "KitHack.py", line 20, in <module>
    from lib import kitools
  File "/root/KitHack/lib/kitools.py", line 15, in <module>
    from KitHack import main
  File "/root/KitHack/KitHack.py", line 21, in <module>
    from lib.network import run_network
  File "/root/KitHack/lib/network.py", line 14, in <module>
    from zenipy.zenipy import entry as entry_token, error as Error
  File "/usr/local/lib/python3.7/dist-packages/zenipy/__init__.py", line 1, in <module>
    from .zenipy import (
  File "/usr/local/lib/python3.7/dist-packages/zenipy/zenipy.py", line 5, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available**

**Comment by AdrMXR** [comment]
Hello, that problem occurs because you need to install the `gtk` package, try the following and let me know if it is solved.
```bash
sudo apt-get install libgtk-3-dev
sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
```

**Comment by xSnkz** [comment]
It works now. Thank you for your help.
