### ISSUE TITLE
sudo python3 KitHack.py

### ISSUE THREAD

**Issue by DialberTrack** [AdrMXR/KitHack#34]
### Información
1. **Version de KitHack utilizada: `La Ultima`** 
2. **Distribución Linux utilizada: `Ubuntu (WSL)`**
3. **Asunto del problema: `Error al ejecutar la herramienta`**

### Stack trace
```
Traceback (most recent call last):
  File "KitHack.py", line 20, in <module>
    from lib import kitools
  File "/home/asd/KitHack/lib/kitools.py", line 15, in <module>
    from KitHack import main
  File "/home/asd/KitHack/KitHack.py", line 21, in <module>
    from lib.network import run_network
  File "/home/asd/KitHack/lib/network.py", line 14, in <module>
    from zenipy.zenipy import entry as entry_token, error as Error
  File "/usr/local/lib/python3.8/dist-packages/zenipy/__init__.py", line 1, in <module>
    from .zenipy import (
  File "/usr/local/lib/python3.8/dist-packages/zenipy/zenipy.py", line 5, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by AdrMXR** [comment]
It's problem of the library gtk3
Run the commands:

`sudo apt-get install libgtk-3-dev
apt install -y gir1.2-gtk-3.0
`
