### ISSUE TITLE
I keep geting this error message

### ISSUE THREAD

**Issue by tsiw247** [AdrMXR/KitHack#35]
Traceback (most recent call last):
  File "/home/kali/KitHack/KitHack.py", line 20, in <module>
    from lib import kitools
  File "/home/kali/KitHack/lib/kitools.py", line 15, in <module>
    from KitHack import main
  File "/home/kali/KitHack/KitHack.py", line 21, in <module>
    from lib.network import run_network
  File "/home/kali/KitHack/lib/network.py", line 14, in <module>
    from zenipy.zenipy import entry as entry_token, error as Error
  File "/usr/local/lib/python3.9/site-packages/zenipy/__init__.py", line 1, in <module>
    from .zenipy import (
  File "/usr/local/lib/python3.9/site-packages/zenipy/zenipy.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by AdrMXR** [comment]
Run the command:
`sudo apt install --reinstall python3-gi`

**Comment by tsiw247** [comment]
I have run this command but still it the program is not running..... the same error message

**Comment by tory1103** [comment]
try this one: sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0

**Comment by songrita** [comment]
i have the same error
Traceback (most recent call last):
  File "/home/songra/KitHack/KitHack.py", line 14, in <module>
    import requests 
ModuleNotFoundError: No module named 'requests'

**Comment by tory1103** [comment]
try installing requests library : python3 -m pip install requests

**Comment by AdrMXR** [comment]
> 
solve your problem?

**Comment by AdrMXR** [comment]
@songrita you solve your problem?

**Comment by Denvora1** [comment]
I have this error , what I can do?
Traceback (most recent call last):
  File "/home/kali/KitHack/KitHack.py", line 19, in <module>
    from lib.banners import *
ModuleNotFoundError: No module named 'lib.banners'
