### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by Big0tez** [AdrMXR/KitHack#49]
Hola, tengo el siguiente error al ejecutar la herramienta:
```
└─# kithack               
Traceback (most recent call last):
  File "/home/kali/Desktop/KitHack/KitHack.py", line 18, in <module>
    from tkinter import Tk, filedialog
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```
Alguna solucion?, gracias de antemano.

**Comment by AdrMXR** [comment]
Execute:
`sudo apt-get install python3.7-tk `
