### ISSUE TITLE
No module named 'lib.banners

### ISSUE THREAD

**Issue by rajanmadaan** [AdrMXR/KitHack#53]
python3 KitHack.py         
Traceback (most recent call last):
  File "/home/rajan/KitHack/KitHack.py", line 19, in <module>
    from lib.banners import * 
ModuleNotFoundError: No module named 'lib.banners'

**Comment by arg2022messi** [comment]
python3 KitHack.py   
/usr/local/lib/python3.11/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.2.0)/charset_normalizer (2.0.8) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/kali/Documentos/Herramientas/KitHack/KitHack.py", line 19, in <module>
    from lib.banners import *
ModuleNotFoundError: No module named 'lib.banners'
