### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by Dy4nk** [AdrMXR/KitHack#60]
### Información
1. **Version de KitHack utilizada: `(v1.3.2)`** 
2. **Distribución Linux utilizada: `(Ubuntu 22.04 LTS)`**
3. **Asunto del problema: `(Herramienta no instalada`**

### Stack trace
```
root@vultr:~/KitHack# kithack
Traceback (most recent call last):
  File "/root/KitHack/KitHack.py", line 14, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

### More details
En ese apartado agrega todos los detalles necesarios. Por ejemplo:

- Ocurre al usar "kithack" en la terminal

### Questions
1. ¿Que soluciones has tratado de aplicar? Usar el update.sh, intentar instalar con pip "collections".
2. ¿Tienes todo tu sistema de paquetes actualizado? (`apt update && apt upgrade`) Si
2. ¿Cuando instalaste kithack? Hoy

**Note:** NUNCA INCLUIR ESPACIOS AL COLOCAR UN NOMBRE DE SALIDA, NI MUCHO MENOS SELECCIONAR ARCHIVOS (APKS O ICONOS) ALMACENADOS EN CARPETAS CON ESPACIOS, LOS ESPACIOS SON IRECONOCIBLES POR KITHACK

**Comment by haxx12** [comment]
Yeah
